routes/web.php
<?php

use App\Http\Controllers\ArticlesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [ArticlesController::class, 'index'])->name('home');

Route::prefix('client')->name('client.')->group(function (){
    Route::resource('articles', ArticlesController::class)
        ->only(['create', 'store'])->middleware('auth');
    Route::resource('articles', ArticlesController::class)
        ->only(['index', 'show']);
});

Route::prefix('admin')->name('admin.')->middleware('ifadmin')->group(function (){
    Route::resource('articles', \App\Http\Controllers\Admin\ArticlesController::class)
        ->except(['create', 'store', 'show']);
});

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Article extends Model
{
    use HasFactory;

    /**
     * @var string[]
     */
    protected $fillable = ['body', 'user_id', 'publication_date', 'approved'];

    /**
     * @var string[]
     */
    protected $casts = [
        'publication_date' => 'datetime',
        'approved' => 'boolean',
    ];

    /**
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'is_admin',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'is_admin' => 'boolean'
    ];

    /**
     * @return HasMany
     */
    public function articles(): HasMany
    {
        return $this->hasMany(Article::class);
    }
}

app/Http/Controllers/Admin/ArticlesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\ArticleRequest;
use App\Http\Requests\ArticleUpdateRequest;
use App\Models\Article;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class ArticlesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index(): View|Factory|Application
    {
        $articles = Article::orderBy('id', 'desc')->paginate(5);
        return view('admin.articles.index', compact('articles'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Article $article
     * @return Application|Factory|View
     */
    public function edit(Article $article): View|Factory|Application
    {
        return view('admin.articles.edit', compact('article'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ArticleUpdateRequest $request
     * @param Article $article
     * @return RedirectResponse
     */
    public function update(ArticleUpdateRequest $request, Article $article): RedirectResponse
    {
        $article->update($request->all());

        return redirect()->route('admin.articles.index')->with('status', 'article successfully updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Article $article
     * @return RedirectResponse
     */
    public function destroy(Article $article): RedirectResponse
    {
        $article->delete();

        return redirect()->route('admin.articles.index')->with('status', 'article successfully deleted!');
    }
}

app/Http/Controllers/ArticlesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ArticleRequest;
use App\Models\Article;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class ArticlesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index(): View|Factory|Application
    {
        $articles = Article::where('approved', true)->whereDate('publication_date', '<=', now())->paginate(9);
        return view('client.articles.index', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create(): View|Factory|Application
    {
        return view('client.articles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ArticleRequest $request
     * @return RedirectResponse
     */
    public function store(ArticleRequest $request): RedirectResponse
    {
        $article = new Article($request->all());
        $article->user_id = $request->user()->id;
        $article->save();

        return redirect()->route('client.articles.index')->with('status', 'successfully created article!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Article  $article
     * @return Application|Factory|View
     */
    public function show(Article $article): View|Factory|Application
    {
        return view('client.articles.show', compact('article'));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/admin/articles/edit.blade.php
@extends('layouts.admin')

@section('content')

    <form method="POST" action="{{route('admin.articles.update', ['article' => $article])}}">
        @csrf
        @method('put')
        <div class="form-group">
            <h4>{{$article->user->name}}</h4>
            <label for="body"><b>Article text</b></label>
            <textarea class="form-control" name="body" id="body" cols="30" rows="10" placeholder="Write here...">{{$article->body}}</textarea>
            @error('body')
            <div class="alert alert-danger">{{$message}}</div>
            @enderror
        </div>

        @if(!$article->approved)
        <div class="form-group">
            <label for="approved"><b>Approve this article?</b></label>
            <select class="form-control" name="approved" id="approved">
                <option value="1">Yes</option>
                <option value="0">No</option>
            </select>
            @error('approved')
            <div class="alert alert-danger">{{$message}}</div>
            @enderror
        </div>
        @endif

        @if(is_null($article->publication_date))
        <div class="form-group">
            <label for="publication_date">Set date:</label>
            <input class="form-check" type="date" name="publication_date" id="publication_date">
            @error('publication_date')
            <div class="alert alert-danger">{{$message}}</div>
            @enderror
        </div>
        @endif

        <button type="submit" class="btn btn-primary mt-2">Save</button>
    </form>

@endsection

resources/views/admin/articles/index.blade.php
@extends('layouts.admin')

@section('content')

    <h1>All articles</h1>

    @if($articles->count() > 0)

        <table class="table table-dark table-striped">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Author</th>
                <th scope="col">Body</th>
                <th scope="col">Created at</th>
                <th scope="col">Published at</th>
                <th scope="col">Approved</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach($articles as $article)
            <tr>
                <th scope="row">{{$article->id}}</th>
                <td>{{$article->user->name}}</td>
                <td>
                        <span class="d-inline-block text-break">
                            {{$article->body}}
                        </span>
                </td>
                <td>{{$article->created_at->format('d M Y - H:i')}}</td>
                <td>
                    @if(!is_null($article->publication_date))
                    {{$article->publication_date->format('d M Y - H:i')}}
                    @else
                        <p>Not published</p>
                    @endif
                </td>
                <td>
                    @if($article->approved)
                    Yes
                    @else
                    check edit to approve
                    @endif
                </td>
                <td>
                    <div class="btn-group">
                    <a class="btn btn-sm btn-outline-warning" type="button" href="{{route('admin.articles.edit', $article)}}">Edit</a>
                        <form method="POST" action="{{route('admin.articles.destroy', $article)}}">
                            @csrf
                            @method('delete')
                            <button class="btn btn-sm btn-outline-danger" type="submit">Delete</button>
                        </form>
                    </div>

                </td>
            </tr>
            @endforeach
            </tbody>
        </table>

        <div class="row justify-content-md-center p-5">
            <div class="col-md-auto">
                {{ $articles->links('pagination::bootstrap-4') }}
            </div>
        </div>

    @else

    <p>No articles</p>

    @endif

@endsection

resources/views/client/articles/create.blade.php
@extends('layouts.app')

@section('content')

    <form method="POST" action="{{route('client.articles.store')}}">
        @csrf
        <div class="form-group">
            <label for="body"><b>Article text</b></label>
            <textarea class="form-control" name="body" id="body" cols="30" rows="10" placeholder="Write here..."></textarea>
            @error('body')
            <div class="alert alert-danger">{{$message}}</div>
            @enderror
        </div>

        <button type="submit" class="btn btn-primary mt-2">Save</button>
    </form>

@endsection

resources/views/client/articles/index.blade.php
@extends('layouts.app')

@section('content')

    <h1>All articles</h1>

    @auth()
        <a class="btn btn-outline-primary mb-2" href="{{route('client.articles.create')}}">Create new article</a>
    @endauth

    @if($articles->count() > 0)

        <div class="row row-cols-1 row-cols-md-3 g-4">
        @foreach($articles as $article)

                <div class="col mb-2">
                    <div class="card h-100">
                        <div class="card-body">
                            <h5 class="card-title">{{$article->user->name}}</h5>
                            <p class="card-text text-truncate">
                                <a href="{{route('client.articles.show', ['article' => $article])}}">{{$article->body}}</a>
                            </p>
                            <small class="text-muted">Create date: {{$article->created_at->format('d M Y - H:i')}}</small>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">Publication date: {{$article->publication_date->format('d M Y - H:i')}}</small>
                        </div>
                    </div>
                </div>

        @endforeach
    </div>

        <div class="row justify-content-md-center pt-5">
            <div class="col-md-auto">
                {{ $articles->withQueryString()->links('pagination::bootstrap-4') }}
            </div>
        </div>

    @else

    <p>No articles</p>

    @endif

@endsection

resources/views/client/articles/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="col mb-2">
        <div class="card h-100">
            <div class="card-body">
                <h5 class="card-title">{{$article->user->name}}</h5>
                <p class="card-text">
                    {{$article->body}}
                </p>
                <small class="text-muted">Create date: {{$article->created_at->format('d M Y - H:i')}}</small>
            </div>
            <div class="card-footer">
                <small class="text-muted">Publication date: {{$article->publication_date->format('d M Y - H:i')}}</small>
            </div>
        </div>
    </div>

    <a class="btn btn-outline-primary" href="{{route('client.articles.index')}}">Go back</a>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/admin.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                Best Articles
            </a>
            <a class="navbar-brand" href="{{ route('admin.articles.index') }}">
                Admin
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        @if (Route::has('login'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                        @endif

                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }}
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        <div class="container">
            @if (session('status'))
                <div class="alert alert-success" role="alert">
                    {{session('status')}}
                </div>
            @endif
            @yield('content')
        </div>
    </main>
</div>
</body>
</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    Best Articles
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            <div class="container">
                @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{session('status')}}
                    </div>
                @endif
                @yield('content')
            </div>
        </main>
    </div>
</body>
</html>